=== DavidP1996erea/XMLXSD/PruebaExamen/prueba3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="centroMalaga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="calificaciones" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Datos">

                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string"/>
                                        <xs:element name="Apellidos" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Materia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OACE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Cuestionario" type="notas"/>
                                                    <xs:element name="Tareas" type="notas"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="EEE">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Cuestionario" type="notas"/>
                                                    <xs:element name="Tareas" type="notas"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="notas">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== DavidP1996erea/XMLXSD/PruebaExamen/prueba3.xml
<?xml version="1.0" encoding="UTF-8"?>
<centroMalaga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="prueba3.xsd">

    <calificaciones>
        <Datos>
            <Nombre>David</Nombre>
            <Apellidos>Perea Garcia</Apellidos>
        </Datos>
        <Materia>
            <OACE>
                <Cuestionario>9</Cuestionario>
                <Tareas>7</Tareas>
            </OACE>
            <EEE>
                <Cuestionario>5</Cuestionario>
                <Tareas>2</Tareas>
            </EEE>
        </Materia>
    </calificaciones>

</centroMalaga>
